Data Exploration of medici_transactions.csv/.json files:

## Data Generation and Validation Summary

Three Python scripts were used to prepare and validate the Medici Bank transaction dataset.

### 1. Initial historical data generation

The `generate_historical_data.py` script created 20,000 synthetic, historically themed banking transactions covering 1390–1440. The dataset includes deposits, withdrawals, loans, loan repayments, bills of exchange, operating expenses, alum trading, war financing, and the Council of Constance ransom payment.

### 2. Dataset expansion and embezzlement trail

The `generate_additional_data.py` script added 60,000 legitimate transactions and 230 intentionally suspicious operating-expense transactions. These suspicious payments:

- Total 95,610 florins
- Occur between January 3, 1420 and December 26, 1424
- Originate exclusively from the Florence branch
- Are paid to the fictitious vendor `Ser Benedetto Forniture`
- Use repetitive, mostly round payment amounts and occur at unusually regular intervals

After expansion, the dataset contains 80,230 transactions.

### 3. Data validation

The `validate_transactions.py` script confirmed that both the CSV and JSON datasets are structurally valid. All 80,230 transactions passed the accounting validation with no errors.

- Total debits: 21,612,302,640.94 florins
- Total credits: 21,612,302,640.94 florins
- Debit-credit difference: 0.00 florins
- CSV validation: Passed
- JSON validation: Passed
- Date coverage: 1390–1440, spanning 51 years

The equality of total debits and credits confirms that the dataset follows double-entry accounting principles.

1. **CSV - Load & Structure Check**
2. **Purpose**: Load CSV file into DF and check to see how the data is organized/structured
3. **Why**: To investigate how many records, columns, etc are present in the dataset
4. **Method**: Use basic panda exploration commands like head, tail, info to get a better idea of the dataset
5. **Findings**:
- After running generate_historical_data.py found only 20K historical  transactions then ran generate_additonal_data.py to load another 60K transactions which expanded to over 80K with a 230 embezzlement transactions.
- Total transactions after validating data = 80,230.
- There are 13 columns contain relevant information: referencing branch, counterparty, credit_account, credit_account_2, credit_amount, credit_amount_2, currency, date, debit_account, debit_amount, description, id, type.
- There 65,632 null transactions credit_account_2/credit_amount_2. Transactions cover 1390-01-01 to 1440-12-31.

In [1]:
import pandas as pd

In [2]:
df_csv = pd.read_csv("medici_transactions.csv")

In [3]:
print("Data loaded sucessfully!")

Data loaded sucessfully!

In [4]:
df_csv.shape

(80230, 13)

In [5]:
df_csv.head()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
0,Florence,Republic of Florence,Cash,NaN,82833.66,NaN,florin,1390-01-01,Loans Receivable - Government,82833.66,Emergency war financing for Florence defense,1,war_financing
1,Florence,Republic of Florence,Cash,NaN,124432.65,NaN,florin,1390-01-01,Loans Receivable - Government,124432.65,Loan to Venice for Lombardy Wars operations,2,war_financing
2,Bruges,Gold Merchant,Cash,NaN,42534.83,NaN,florin,1390-01-01,Loans Receivable,42534.83,Loan issued to Gold Merchant from Bruges branch,3,loan_issuance
3,Florence,Republic of Florence,Cash,NaN,1617678.46,NaN,florin,1390-01-01,Loans Receivable - Government,1617678.46,War financing for Florentine operations agains...,4,war_financing
4,Florence,Republic of Florence,Cash,NaN,27742.84,NaN,florin,1390-01-01,Loans Receivable - Government,27742.84,Loan to Venice for Lombardy Wars operations,5,war_financing

In [6]:
df_csv.tail()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
80225,Geneva,Transfer to Venice,Cash,Exchange Fee Revenue,3091.96,71.82,florin,1440-12-30,Due from Venice,3163.78,Bill of exchange from Geneva to Venice,80226,bill_of_exchange
80226,Florence,Republic of Florence,Cash,NaN,197709.59,NaN,florin,1440-12-30,Loans Receivable - Government,197709.59,Loan to Venice for Lombardy Wars operations,80227,war_financing
80227,Venice,Marquis,Loans Receivable,Interest Income,120700.73,28968.18,florin,1440-12-31,Cash,149668.91,Loan repayment from Marquis with interest,80228,loan_repayment
80228,Geneva,Gold Merchant,Cash,NaN,69318.55,NaN,florin,1440-12-31,Loans Receivable,69318.55,Loan issued to Gold Merchant from Geneva branch,80229,loan_issuance
80229,Milan,Wine Trader,Loans Receivable,Interest Income,313446.76,72092.75,florin,1440-12-31,Cash,385539.51,Loan repayment from Wine Trader with interest,80230,loan_repayment

In [7]:
df_csv.columns.tolist()

['branch',
 'counterparty',
 'credit_account',
 'credit_account_2',
 'credit_amount',
 'credit_amount_2',
 'currency',
 'date',
 'debit_account',
 'debit_amount',
 'description',
 'id',
 'type']

In [8]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 80230 entries, 0 to 80229
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   branch            80230 non-null  str
 1   counterparty      80230 non-null  str
 2   credit_account    80230 non-null  str
 3   credit_account_2  14598 non-null  str
 4   credit_amount     80230 non-null  float64
 5   credit_amount_2   14598 non-null  float64
 6   currency          80230 non-null  str
 7   date              80230 non-null  str
 8   debit_account     80230 non-null  str
 9   debit_amount      80230 non-null  float64
 10  description       80230 non-null  str
 11  id                80230 non-null  int64
 12  type              80230 non-null  str
dtypes: float64(3), int64(1), str(9)
memory usage: 8.0 MB

In [9]:
df_csv.isnull().sum()

branch                  0
counterparty            0
credit_account          0
credit_account_2    65632
credit_amount           0
credit_amount_2     65632
currency                0
date                    0
debit_account           0
debit_amount            0
description             0
id                      0
type                    0
dtype: int64

In [10]:
df_csv["date"] = pd.to_datetime(df_csv["date"])

print("Date data type:", df_csv["date"].dtype)
print("Earliest transaction:", df_csv["date"].min())
print("Latest transaction:", df_csv["date"].max())

Date data type: datetime64[us]
Earliest transaction: 1390-01-01 00:00:00
Latest transaction: 1440-12-31 00:00:00

2. **CSV - Currency Consistency Check**
- Purpose: Check to see if there a different currency types within the dataset
- Why: To confirm sure the same currency is being used across the transactions within the dataset
- Method: Noticed currency was a column in the dataset so used value_count to see if all transactions had the same currency
- Findings: There is only 1 currency type across the whole data set, all 80,230 rows

In [11]:
df_csv["currency"].value_counts()

currency
florin    80230
Name: count, dtype: int64

3. **CSV — Branch Distribution**
- **Purpose:** Break down transaction volume by branch to understand which locations dominate the dataset.
- **Why:** Branch is a key filter needed for the dashboard and a required field on every Cleaned Transaction — need to confirm the branch values are clean and match expectations before ingestion module is created.
- **Method:** `value_counts()` on `branch`, both raw counts and normalized percentages.
- **Findings:** Rome leads at 32.77% (26,288 transactions), Florence second at 22.80% (18,295), then Venice, Bruges, London, Avignon, Milan, and Geneva clustered between 6.95%–9.23%. Constance has exactly 1 transaction (0.00%), which was confirmed against the branch and `ransom_payment`. These percentages line up closely with the expected distribution in `TRANSACTION_DATA.md` (Rome 33.1%, Florence 22.1%, Venice 9.7%), so no major deviation flagged here.

In [12]:
branch_counts = df_csv["branch"].value_counts()

branch_counts

branch
Rome         26288
Florence     18295
Venice        7407
Bruges        5700
London        5663
Avignon       5663
Milan         5638
Geneva        5575
Constance        1
Name: count, dtype: int64

In [13]:
branch_percentages = df_csv["branch"].value_counts(normalize=True).mul(100).round(2)

branch_percentages

branch
Rome         32.77
Florence     22.80
Venice        9.23
Bruges        7.10
London        7.06
Avignon       7.06
Milan         7.03
Geneva        6.95
Constance     0.00
Name: proportion, dtype: float64

In [14]:
df_csv[df_csv["branch"] =="Constance"]

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
39791,Constance,Council of Constance - Pope John XXIII Ransom,Cash,NaN,35000.0,NaN,florin,1415-05-29,Papal Receivable,35000.0,"Payment of 35,000 florin ransom for Pope John ...",39792,ransom_payment

In [15]:
df_csv[df_csv["type"] =="ransom_payment"]

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
39791,Constance,Council of Constance - Pope John XXIII Ransom,Cash,NaN,35000.0,NaN,florin,1415-05-29,Papal Receivable,35000.0,"Payment of 35,000 florin ransom for Pope John ...",39792,ransom_payment

## 4. CSV — Transaction Type Distribution

- **Purpose:** Break down transaction volume by type to see which categories make up the dataset.
- **Why:** `type` must be one of the 9 values defined in the data contract (`deposit`, `withdrawal`, `loan_issuance`, `loan_repayment`, `operating_expense`, `war_financing`, `bill_of_exchange`, `alum_trade`, `ransom_payment`) — confirming the value set and distribution here catches any stray/typo'd type before ingestion.
- **Method:** `value_counts()` on `type`, both raw counts and normalized percentages.
- **Findings:** All 9 expected types are present, no unexpected values. `deposit` is largest at 31.20% (25,031), followed by `operating_expense` at 13.69% (10,987) and `war_financing` at 13.17% (10,568). `ransom_payment` is a single transaction (0.00%), consistent with the one historical ransom event. Distribution closely matches `TRANSACTION_DATA.md`'s expected percentages.

In [16]:
transaction_type_counts = df_csv["type"].value_counts()

transaction_type_counts

type
deposit              25031
operating_expense    10987
war_financing        10568
loan_repayment        8170
loan_issuance         7478
bill_of_exchange      6428
withdrawal            6374
alum_trade            5193
ransom_payment           1
Name: count, dtype: int64

In [17]:
transaction_type_percentages=(
    df_csv["type"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

transaction_type_percentages

type
deposit              31.20
operating_expense    13.69
war_financing        13.17
loan_repayment       10.18
loan_issuance         9.32
bill_of_exchange      8.01
withdrawal            7.94
alum_trade            6.47
ransom_payment        0.00
Name: proportion, dtype: float64

## 5. JSON — Load and Structure Check

- **Purpose:** Load the JSON transaction file into a pandas DataFrame and inspect its structure.
- **Why:** The ingestion layer must support both CSV and JSON. Inspecting the JSON file confirms that it contains the expected records and fields and identifies any formatting differences that the ingestion module must handle.
- **Method:** Used `pd.read_json()` to load the file, then inspected its first and last rows, shape, data types, null counts, and date range.
- **Findings:** The JSON file contains 80,230 transactions and the same 13 columns as the CSV file. Its transactions cover 1 January 1390 through 31 December 1440. The optional `credit_account_2` and `credit_amount_2` fields contain a mixture of null values and empty strings, unlike the CSV file, which represents the missing values consistently as nulls. The ingestion layer must therefore normalize both representations.

In [18]:
df_json = pd.read_json('medici_transactions.json')

In [19]:
print(" Data loaded successfully!")

 Data loaded successfully!

In [20]:
df_json.head()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
0,Florence,Republic of Florence,Cash,,82833.66,,florin,1390-01-01,Loans Receivable - Government,82833.66,Emergency war financing for Florence defense,1,war_financing
1,Florence,Republic of Florence,Cash,NaN,124432.65,NaN,florin,1390-01-01,Loans Receivable - Government,124432.65,Loan to Venice for Lombardy Wars operations,2,war_financing
2,Bruges,Gold Merchant,Cash,NaN,42534.83,NaN,florin,1390-01-01,Loans Receivable,42534.83,Loan issued to Gold Merchant from Bruges branch,3,loan_issuance
3,Florence,Republic of Florence,Cash,NaN,1617678.46,NaN,florin,1390-01-01,Loans Receivable - Government,1617678.46,War financing for Florentine operations agains...,4,war_financing
4,Florence,Republic of Florence,Cash,NaN,27742.84,NaN,florin,1390-01-01,Loans Receivable - Government,27742.84,Loan to Venice for Lombardy Wars operations,5,war_financing

In [21]:
df_json.tail()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
80225,Geneva,Transfer to Venice,Cash,Exchange Fee Revenue,3091.96,71.82,florin,1440-12-30,Due from Venice,3163.78,Bill of exchange from Geneva to Venice,80226,bill_of_exchange
80226,Florence,Republic of Florence,Cash,NaN,197709.59,NaN,florin,1440-12-30,Loans Receivable - Government,197709.59,Loan to Venice for Lombardy Wars operations,80227,war_financing
80227,Venice,Marquis,Loans Receivable,Interest Income,120700.73,28968.18,florin,1440-12-31,Cash,149668.91,Loan repayment from Marquis with interest,80228,loan_repayment
80228,Geneva,Gold Merchant,Cash,,69318.55,,florin,1440-12-31,Loans Receivable,69318.55,Loan issued to Gold Merchant from Geneva branch,80229,loan_issuance
80229,Milan,Wine Trader,Loans Receivable,Interest Income,313446.76,72092.75,florin,1440-12-31,Cash,385539.51,Loan repayment from Wine Trader with interest,80230,loan_repayment

In [22]:
df_json.shape

(80230, 13)

In [23]:
df_json.info()

<class 'pandas.DataFrame'>
RangeIndex: 80230 entries, 0 to 80229
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   branch            80230 non-null  str
 1   counterparty      80230 non-null  str
 2   credit_account    80230 non-null  str
 3   credit_account_2  30930 non-null  str
 4   credit_amount     80230 non-null  float64
 5   credit_amount_2   30930 non-null  object
 6   currency          80230 non-null  str
 7   date              80230 non-null  datetime64[us]
 8   debit_account     80230 non-null  str
 9   debit_amount      80230 non-null  float64
 10  description       80230 non-null  str
 11  id                80230 non-null  int64
 12  type              80230 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(8)
memory usage: 8.0+ MB

In [24]:
df_json.isnull().sum()

branch                  0
counterparty            0
credit_account          0
credit_account_2    49300
credit_amount           0
credit_amount_2     49300
currency                0
date                    0
debit_account           0
debit_amount            0
description             0
id                      0
type                    0
dtype: int64

In [25]:
df_json["credit_account_2"].isnull().sum()

np.int64(49300)

In [26]:
df_json["date"] = pd.to_datetime(df_json["date"])

print("Date data type:", df_json["date"].dtype)
print("Earliest transaction:", df_json["date"].min())
print("Latest transaction:", df_json["date"].max())

Date data type: datetime64[us]
Earliest transaction: 1390-01-01 00:00:00
Latest transaction: 1440-12-31 00:00:00

6. **CSV vs JSON Cross Validation:**
- Purpose: to confirm the data in the CSV and JSON files have the same underlying data.
- Why: Confirms the 2 export files can be used in later phases of the project if one needs to be favored over the other; so both can be trusted
- Method: Compared len() to count the rows, and used set()/value counts() on `id` and `type` to confirm matching transactions and categories
- Findings: four checks confirmed True: row count match (80,230 = 80,230), transaction ID sets match exactly, `type` category sets match, and `type` value_counts match per-category. Confirms CSV and JSON represent the same 80,230 transactions. One structural difference noted despite the match: `credit_account_2`/`credit_amount_2` null counts differ between files (CSV: 65,632 null; JSON: 49,300 null) — the JSON encodes some blank values as empty strings rather than true nulls, inconsistently within the same file (see Section 5). This doesn't affect transaction identity, but ingestion code will need to handle both blank representations for this field.

In [27]:
len(df_csv) == len(df_json) #shows if both files have the same row count

True

In [28]:
set(df_csv["id"]) == set(df_json["id"]) #shows if both files have the same id's or transactions

True

In [29]:
set(df_csv["type"]) == set(df_json["type"]) # shows is both files have the same categories?

True

In [30]:
df_csv["type"].value_counts().sort_index().equals(df_json["type"].value_counts().sort_index())  # shows if both files have same counts per category?

True

## 7. CSV — Balancing Rule Check

- **Purpose:** Verify every transaction satisfies double-entry accounting before ingestion applies the same rule.
- **Why:** The data contract (Cleaned Transaction, `data-contracts.md`) requires `debit_amount == credit_amount + credit_amount_2` as the validation rule enforced before a row becomes a Cleaned Transaction; rows that fail are logged and excluded. Confirming this in raw data first tells the team what exclusion rate to expect.
- **Method:** Computed `abs(debit_amount - (credit_amount + credit_amount_2.fillna(0))) < 0.01` across all rows (tolerance used instead of exact equality due to float rounding), then counted True/False.
- **Findings:** All 80,230 rows balance; `True: 80230`, zero failures. The contract's exclusion logic won't drop any rows on this dataset; every transaction is already double-entry-clean.

In [55]:
balanced = (df_csv["debit_amount"] - (df_csv["credit_amount"] + df_csv["credit_amount_2"].fillna(0))).abs() < 0.01
balanced.value_counts()

True    80230
Name: count, dtype: int64

## 8. CSV — Branch Normalization Check

- **Purpose:** Confirm `branch` values are clean with no casing or whitespace hiding as separate categories.
- **Why:** The contract requires `branch` to be "normalized: consistent capitalization, no trailing whitespace" by the time it reaches a Cleaned Transaction; checking the raw data first shows whether ingestion has any normalization work to do here.
- **Method:** Compared `.unique()` (raw distinct values) against `.str.strip().str.lower().nunique()` (case/whitespace-normalized count).
- **Findings:** Both return 9; `Florence, Bruges, Geneva, Venice, Rome, London, Avignon, Milan, Constance`, no casing or whitespace duplicates. Branch data is already clean.

In [33]:
df_csv["branch"].str.strip().str.lower().nunique()  # compares to the 9 branches we already confirmed

9

In [34]:
df_csv["branch"].unique()

<StringArray>
[ 'Florence',    'Bruges',    'Geneva',    'Venice',      'Rome',    'London',
   'Avignon',     'Milan', 'Constance']
Length: 9, dtype: str

## 9. CSV — Duplicate Transaction Check

- **Purpose:** Identify rows that duplicate another transaction on the fields that define a duplicate.
- **Why:** The data contract's `is_duplicate` field is defined with 6 columns : `(date, branch, type, counterparty, debit_amount, credit_account)`. Duplicates are required to be flagged, never silently dropped (Section 4.2). So ingestion needs to know how many exist and replicate this exact matching logic.
- **Method:** `df_csv.duplicated(subset=[date, branch, type, counterparty, debit_amount, credit_account], keep=False)`, which flags every row in a duplicate group.
- **Findings:** `(0, 13)` so there are no duplicate transactions found in the 6 columns specified. No rows for ingestion's `is_duplicate` flag to catch in this dataset.

In [35]:
dup_cols = ["date", "branch", "type", "counterparty", "debit_amount", "credit_account"]
duplicates = df_csv[df_csv.duplicated(subset=dup_cols, keep=False)]
duplicates.shape

(0, 13)

## 10. CSV — Account Name Inventory

- **Purpose:** List the distinct account names used in `debit_account` and `credit_account`.
- **Why:** The contract requires `debit_account_type`/`credit_account_type` to be inferred from these account name strings (same logic as `medici-banking.py`). Ingestion needs a full inventory to build that mapping correctly.
- **Method:** `.unique()` on `debit_account` and `credit_account`.
- **Findings:** `debit_account` has 19 distinct values (a mix of expense accounts, receivables, and inter-branch "Due from X" accounts); `credit_account` has only 4 (`Cash`, `Loans Receivable`, `Trading Revenue`, `Deposits Payable`). They dont match up but that could make sense as most transaction types debit a specific account but credit back to one of a small set of core accounts. `credit_account`'s account to type mapping will be simple; `debit_account`'s 19 values need a more complete lookup table before ingestion can populate `debit_account_type`.

In [36]:
df_csv["debit_account"].unique()

<StringArray>
['Loans Receivable - Government',              'Loans Receivable',
                          'Cash',              'Deposits Payable',
               'Due from Geneva',                'Due from Milan',
                         'Wages',                      'Security',
                          'Rent',               'Due from Venice',
                      'Supplies',                   'Maintenance',
                 'Due from Rome',               'Due from Bruges',
              'Courier Services',             'Due from Florence',
               'Due from London',              'Due from Avignon',
              'Papal Receivable']
Length: 19, dtype: str

In [37]:
df_csv["credit_account"].unique()

<StringArray>
['Cash', 'Loans Receivable', 'Trading Revenue', 'Deposits Payable']
Length: 4, dtype: str

In [38]:
df_csv["credit_account_2"].unique()

<StringArray>
[nan, 'Interest Income', 'Exchange Fee Revenue']
Length: 3, dtype: str

## 11. CSV — credit_account_2 / credit_amount_2  dealing with Nulls

- **Purpose:** Confirm whether `credit_account_2` and `credit_amount_2` are null together consistently.
- **Why:** The data contract defines an asymmetric rule for these two fields: blank `credit_amount_2` → `0` (never `None`), while blank `credit_account_2` → `None`. Before ingestion applies that transformation, need to confirm the raw data's null pattern is consistent to start from.
- **Method:** `(credit_account_2.isnull() == credit_amount_2.isnull()).value_counts()`.
- **Findings:** `True: 80230` in the raw CSV, the two columns are null together on every row, with no row having one filled and the other blank. Clean starting point: ingestion's asymmetric transform (amount → `0`, account → stays `None`) can be applied without needing to handle any misaligned edge cases first. Also confirmed via `.unique()`: `credit_account_2` only takes 3 values: `NaN`, `Interest Income`, `Exchange Fee Revenue`

In [39]:
# Are the two null columns the same; does account_2 being null match amount_2 being null?
(df_csv["credit_account_2"].isnull() == df_csv["credit_amount_2"].isnull()).value_counts()

True    80230
Name: count, dtype: int64

## 12. CSV — Transaction Counts by Year

- **Purpose:** Count the number of transactions recorded during each year in the dataset.
- **Why:** Transaction counts by year are a required Phase 1 summary and help confirm that the dataset covers the complete historical period without unexpected missing years.
- **Method:** Derived a `year` column from the converted `date` column using `.dt.year`, grouped the records by year, and counted the number of transactions in each group.
- **Findings:** The dataset contains transactions for all 51 years from 1390 through 1440. The yearly counts sum to the complete dataset total of 80,230 transactions. The highest annual count occurs in 1424 with 1,651 transactions, while the lowest occurs in 1433 with 1,479 transactions. The relatively consistent annual counts show that the data is distributed across the full historical period rather than concentrated in only a few years.

In [45]:
df_csv["year"] = df_csv["date"].dt.year
transactions_by_year = df_csv.groupby("year").size()
print(transactions_by_year.to_string())

year
1390    1632
1391    1520
1392    1614
1393    1519
1394    1565
1395    1606
1396    1554
1397    1547
1398    1602
1399    1571
1400    1618
1401    1515
1402    1557
1403    1561
1404    1600
1405    1583
1406    1555
1407    1593
1408    1518
1409    1552
1410    1618
1411    1554
1412    1531
1413    1565
1414    1544
1415    1563
1416    1614
1417    1580
1418    1590
1419    1526
1420    1603
1421    1641
1422    1609
1423    1534
1424    1651
1425    1513
1426    1625
1427    1502
1428    1572
1429    1525
1430    1624
1431    1638
1432    1547
1433    1479
1434    1589
1435    1600
1436    1555
1437    1623
1438    1609
1439    1540
1440    1584

In [46]:
print("Years represented:", transactions_by_year.size)
print("Total transactions:", transactions_by_year.sum())

Years represented: 51
Total transactions: 80230

## 13. CSV — Total Florin Volume by Branch and Transaction Type

- **Purpose:** Calculate the total florin value of transactions for every branch and transaction-type combination.
- **Why:** This summary is a required Phase 1 deliverable and shows which activities contribute the greatest financial volume within each branch. It also provides a baseline for the branch-level KPI calculations developed in later phases.
- **Method:** Grouped the transactions by `branch` and `type`, summed `debit_amount` for each group, and reshaped the result into a table with branches as rows and transaction types as columns. `debit_amount` was used because it represents the complete value of each balanced transaction; adding debit and credit amounts would count the same transaction twice.
- **Findings:** Florence has the largest total transaction volume, driven primarily by approximately 12.11 billion florins in war-financing activity. Rome has the second-largest volume, led by approximately 5.44 billion florins in deposits. Constance has only one transaction—the 35,000-florin ransom payment; so its total volume is substantially smaller than the operating branches. The results demonstrate that transaction count and transaction value measure different aspects of branch activity: Rome has the most transactions, while Florence has the greatest total florin volume.

In [48]:
transactions_by_branch = df_csv.groupby("branch").size()
print(transactions_by_branch)

branch
Avignon       5663
Bruges        5700
Constance        1
Florence     18295
Geneva        5575
London        5663
Milan         5638
Rome         26288
Venice        7407
dtype: int64

In [49]:
volume_by_branch_and_type = (
    df_csv.groupby(["branch", "type"])["debit_amount"]
    .sum()
)
print(volume_by_branch_and_type.to_string())

branch     type
Avignon    bill_of_exchange     8.893440e+07
           deposit              7.049841e+07
           loan_issuance        1.991768e+08
           loan_repayment       7.244281e+07
           operating_expense    5.300482e+06
           withdrawal           7.063471e+07
Bruges     bill_of_exchange     8.774283e+07
           deposit              7.439378e+07
           loan_issuance        1.931275e+08
           loan_repayment       7.753455e+07
           operating_expense    5.558014e+06
           withdrawal           7.059834e+07
Constance  ransom_payment       3.500000e+04
Florence   alum_trade           5.514821e+07
           bill_of_exchange     1.050327e+08
           deposit              7.014012e+07
           loan_issuance        2.065400e+08
           loan_repayment       7.501422e+07
           operating_expense    5.261333e+06
           war_financing        1.210777e+10
           withdrawal           6.446511e+07
Geneva     bill_of_exchange     9.547641e+07
           deposit              6.142746e+07
           loan_issuance        1.925394e+08
           loan_repayment       6.425023e+07
           operating_expense    5.176832e+06
           withdrawal           6.266515e+07
London     bill_of_exchange     9.373037e+07
           deposit              6.829431e+07
           loan_issuance        1.754385e+08
           loan_repayment       6.318853e+07
           operating_expense    4.980224e+06
           withdrawal           6.309459e+07
Milan      bill_of_exchange     8.455007e+07
           deposit              6.739083e+07
           loan_issuance        1.777170e+08
           loan_repayment       6.607137e+07
           operating_expense    4.752346e+06
           withdrawal           7.010422e+07
Rome       alum_trade           4.685996e+07
           bill_of_exchange     9.105455e+07
           deposit              5.442471e+09
           loan_issuance        2.165955e+08
           loan_repayment       6.453721e+07
           operating_expense    4.584442e+06
           withdrawal           6.759020e+07
Venice     alum_trade           5.264620e+07
           bill_of_exchange     8.588512e+07
           deposit              6.952944e+07
           loan_issuance        2.143599e+08
           loan_repayment       6.424653e+07
           operating_expense    5.258259e+06
           withdrawal           6.048460e+07

In [51]:
volume_table = (
    df_csv.groupby(["branch", "type"])["debit_amount"]
    .sum()
    .unstack(fill_value=0)
)
volume_table.style.format("{:,.2f}")