In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("medici_transactions.csv")

In [3]:
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.shape

(80230, 13)

In [5]:
df.head()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
0,Florence,Republic of Florence,Cash,NaN,82833.66,NaN,florin,1390-01-01,Loans Receivable - Government,82833.66,Emergency war financing for Florence defense,1,war_financing
1,Florence,Republic of Florence,Cash,NaN,124432.65,NaN,florin,1390-01-01,Loans Receivable - Government,124432.65,Loan to Venice for Lombardy Wars operations,2,war_financing
2,Bruges,Gold Merchant,Cash,NaN,42534.83,NaN,florin,1390-01-01,Loans Receivable,42534.83,Loan issued to Gold Merchant from Bruges branch,3,loan_issuance
3,Florence,Republic of Florence,Cash,NaN,1617678.46,NaN,florin,1390-01-01,Loans Receivable - Government,1617678.46,War financing for Florentine operations agains...,4,war_financing
4,Florence,Republic of Florence,Cash,NaN,27742.84,NaN,florin,1390-01-01,Loans Receivable - Government,27742.84,Loan to Venice for Lombardy Wars operations,5,war_financing

In [6]:
df.columns.tolist()

['branch',
 'counterparty',
 'credit_account',
 'credit_account_2',
 'credit_amount',
 'credit_amount_2',
 'currency',
 'date',
 'debit_account',
 'debit_amount',
 'description',
 'id',
 'type']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80230 entries, 0 to 80229
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   branch            80230 non-null  str
 1   counterparty      80230 non-null  str
 2   credit_account    80230 non-null  str
 3   credit_account_2  14598 non-null  str
 4   credit_amount     80230 non-null  float64
 5   credit_amount_2   14598 non-null  float64
 6   currency          80230 non-null  str
 7   date              80230 non-null  str
 8   debit_account     80230 non-null  str
 9   debit_amount      80230 non-null  float64
 10  description       80230 non-null  str
 11  id                80230 non-null  int64
 12  type              80230 non-null  str
dtypes: float64(3), int64(1), str(9)
memory usage: 8.0 MB

In [8]:
df.isnull().sum()

branch                  0
counterparty            0
credit_account          0
credit_account_2    65632
credit_amount           0
credit_amount_2     65632
currency                0
date                    0
debit_account           0
debit_amount            0
description             0
id                      0
type                    0
dtype: int64

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80230 entries, 0 to 80229
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   branch            80230 non-null  str
 1   counterparty      80230 non-null  str
 2   credit_account    80230 non-null  str
 3   credit_account_2  14598 non-null  str
 4   credit_amount     80230 non-null  float64
 5   credit_amount_2   14598 non-null  float64
 6   currency          80230 non-null  str
 7   date              80230 non-null  str
 8   debit_account     80230 non-null  str
 9   debit_amount      80230 non-null  float64
 10  description       80230 non-null  str
 11  id                80230 non-null  int64
 12  type              80230 non-null  str
dtypes: float64(3), int64(1), str(9)
memory usage: 8.0 MB

In [10]:
df.isnull().sum()

branch                  0
counterparty            0
credit_account          0
credit_account_2    65632
credit_amount           0
credit_amount_2     65632
currency                0
date                    0
debit_account           0
debit_amount            0
description             0
id                      0
type                    0
dtype: int64

In [11]:
df["date"] = pd.to_datetime(df["date"])

print("Date data type:", df["date"].dtype)
print("Earliest transaction:", df["date"].min())
print("Latest transaction:", df["date"].max())

Date data type: datetime64[us]
Earliest transaction: 1390-01-01 00:00:00
Latest transaction: 1440-12-31 00:00:00

In [12]:
df["currency"].value_counts()

currency
florin    80230
Name: count, dtype: int64

In [13]:
branch_counts = df["branch"].value_counts()

branch_counts

branch
Rome         26288
Florence     18295
Venice        7407
Bruges        5700
London        5663
Avignon       5663
Milan         5638
Geneva        5575
Constance        1
Name: count, dtype: int64

In [14]:
branch_percentages = df["branch"].value_counts(normalize=True).mul(100).round(2)

branch_percentages

branch
Rome         32.77
Florence     22.80
Venice        9.23
Bruges        7.10
London        7.06
Avignon       7.06
Milan         7.03
Geneva        6.95
Constance     0.00
Name: proportion, dtype: float64

In [15]:
transaction_type_counts = df["type"].value_counts()

transaction_type_counts

type
deposit              25031
operating_expense    10987
war_financing        10568
loan_repayment        8170
loan_issuance         7478
bill_of_exchange      6428
withdrawal            6374
alum_trade            5193
ransom_payment           1
Name: count, dtype: int64

In [16]:
transaction_type_percentages = (
    df["type"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

transaction_type_percentages

type
deposit              31.20
operating_expense    13.69
war_financing        13.17
loan_repayment       10.18
loan_issuance         9.32
bill_of_exchange      8.01
withdrawal            7.94
alum_trade            6.47
ransom_payment        0.00
Name: proportion, dtype: float64

In [17]:
df.tail()

,branch,counterparty,credit_account,credit_account_2,credit_amount,credit_amount_2,currency,date,debit_account,debit_amount,description,id,type
80225,Geneva,Transfer to Venice,Cash,Exchange Fee Revenue,3091.96,71.82,florin,1440-12-30,Due from Venice,3163.78,Bill of exchange from Geneva to Venice,80226,bill_of_exchange
80226,Florence,Republic of Florence,Cash,NaN,197709.59,NaN,florin,1440-12-30,Loans Receivable - Government,197709.59,Loan to Venice for Lombardy Wars operations,80227,war_financing
80227,Venice,Marquis,Loans Receivable,Interest Income,120700.73,28968.18,florin,1440-12-31,Cash,149668.91,Loan repayment from Marquis with interest,80228,loan_repayment
80228,Geneva,Gold Merchant,Cash,NaN,69318.55,NaN,florin,1440-12-31,Loans Receivable,69318.55,Loan issued to Gold Merchant from Geneva branch,80229,loan_issuance
80229,Milan,Wine Trader,Loans Receivable,Interest Income,313446.76,72092.75,florin,1440-12-31,Cash,385539.51,Loan repayment from Wine Trader with interest,80230,loan_repayment